#!/bin/bash

# Give permission for 'csh' to access network configuration
# in order to setup the CAN interface baudrate and +up
# When the file is deleted (rebuild) setcap needs to be run
# again

sudo setcap cap_net_raw,cap_net_admin+ep ./builddir/csh

