# To build/run this image on a Intel based computer, you need to install the "qemu-user-static" package (sudo apt install qemu-user-static)
# then:
# docker build --platform linux/arm/v7 -t sysroot-build -f Dockerfile_gnueabihf .
# Run it:
# docker run -v /full/path/to/sysroot:/sysroot -e LIST_OF_PACKAGES="libcurl4-openssl-dev libzmq3-dev" --platform linux/arm/v7 -it sysroot-build

FROM dtcooper/raspberrypi-os:lite-bookworm

ENV LIST_OF_PACKAGES=libxm2-dev

WORKDIR /root
RUN mkdir /download
RUN mkdir -p /sysroot

COPY make_sysroot.sh .
RUN chmod +x make_sysroot.sh
RUN apt update

CMD ["./make_sysroot.sh"]
